# Generated by Django 2.1.5 on 2019-02-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20190217_0900'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(related_name='favourited_by', to='listings.Listing'),
        ),
    ]
