# Generated by Django 2.1.5 on 2019-03-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourites',
        ),
    ]
