# Generated by Django 2.1.5 on 2019-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_auto_20190304_0602'),
        ('users', '0005_remove_profile_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(related_name='favourited_by', to='listings.Listing'),
        ),
    ]
