# Generated by Django 2.1.5 on 2019-03-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favourites',
            new_name='favourite',
        ),
    ]
