# Generated by Django 2.1.5 on 2019-03-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190304_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite',
        ),
    ]
