# Generated by Django 2.1.5 on 2019-02-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('KB', 'Kabete'), ('NH', 'Nyahururu'), ('DA', 'Dagoretti'), ('RK', 'Ruaka'), ('KT', 'Kitengela'), ('LK', 'Likoni'), ('KR', 'Karen'), ('MS', 'Mombasa'), ('UK', 'Ukunda'), ('LE', 'Kileleshwa'), ('IS', 'Isinya'), ('LO', 'Loresho'), ('NU', 'Nyanyuki'), ('LM', 'Limuru'), ('WS', 'Kahawa West'), ('MV', 'Mvita'), ('OR', 'Ongata Rongai'), ('KS', 'Kiserian'), ('ND', 'Nyandarua'), ('SY', 'Syokimau'), ('LV', 'Lavington'), ('WN', 'Kahawa Wendani'), ('NE', 'Nyeri'), ('KK', 'Kakamega'), ('BU', 'Bungoma'), ('KU', 'Kikuyu'), ('NL', 'Nyali'), ('MA', 'Malindi'), ('LA', 'Langata'), ('NY', 'Nyamira'), ('KL', 'Kilifi'), ('JJ', 'Juja'), ('MC', 'Machakos'), ('SU', 'Kahawa Sukari'), ('MK', 'Mavoko'), ('KW', 'Kwale'), ('NV', 'Naivasha'), ('EL', 'Eldoret'), ('KN', 'Kinoo'), ('KA', 'Kajiado'), ('TH', 'Kithiani'), ('LI', 'Kilimani'), ('KI', 'Kisii'), ('AR', 'Athi River'), ('NA', 'Nakuru'), ('RU', 'Ruiru'), ('KM', 'Kiambu'), ('WE', 'Westlands'), ('WT', 'Watamu'), ('SA', 'Kisauni'), ('MW', 'Msambweni'), ('NG', 'Namanga'), ('NR', 'Narok')], max_length=2),
        ),
    ]
