# Generated by Django 2.1.5 on 2019-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190210_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('ND', 'Nyandarua'), ('NV', 'Naivasha'), ('LO', 'Loresho'), ('KL', 'Kilifi'), ('KR', 'Karen'), ('NH', 'Nyahururu'), ('JJ', 'Juja'), ('LI', 'Kilimani'), ('LM', 'Limuru'), ('KN', 'Kinoo'), ('MW', 'Msambweni'), ('NA', 'Nakuru'), ('OR', 'Ongata Rongai'), ('SY', 'Syokimau'), ('LV', 'Lavington'), ('IS', 'Isinya'), ('MS', 'Mombasa'), ('WS', 'Kahawa West'), ('BU', 'Bungoma'), ('MK', 'Mavoko'), ('NR', 'Narok'), ('KS', 'Kiserian'), ('KU', 'Kikuyu'), ('KT', 'Kitengela'), ('WE', 'Westlands'), ('AR', 'Athi River'), ('KB', 'Kabete'), ('NE', 'Nyeri'), ('KM', 'Kiambu'), ('LE', 'Kileleshwa'), ('WN', 'Kahawa Wendani'), ('RU', 'Ruiru'), ('MC', 'Machakos'), ('TH', 'Kithiani'), ('SU', 'Kahawa Sukari'), ('KK', 'Kakamega'), ('RK', 'Ruaka'), ('DA', 'Dagoretti'), ('NG', 'Namanga'), ('SA', 'Kisauni'), ('KA', 'Kajiado'), ('NU', 'Nyanyuki'), ('KW', 'Kwale'), ('KI', 'Kisii'), ('UK', 'Ukunda'), ('MA', 'Malindi'), ('NL', 'Nyali'), ('EL', 'Eldoret'), ('MV', 'Mvita'), ('LA', 'Langata'), ('NY', 'Nyamira'), ('LK', 'Likoni'), ('WT', 'Watamu')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
