# Generated by Django 2.1.5 on 2019-02-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190210_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('UK', 'Ukunda'), ('KW', 'Kwale'), ('KS', 'Kiserian'), ('KT', 'Kitengela'), ('RK', 'Ruaka'), ('NL', 'Nyali'), ('KK', 'Kakamega'), ('LA', 'Langata'), ('KB', 'Kabete'), ('MV', 'Mvita'), ('MK', 'Mavoko'), ('LO', 'Loresho'), ('MS', 'Mombasa'), ('WN', 'Kahawa Wendani'), ('NE', 'Nyeri'), ('MA', 'Malindi'), ('NY', 'Nyamira'), ('DA', 'Dagoretti'), ('SY', 'Syokimau'), ('OR', 'Ongata Rongai'), ('LK', 'Likoni'), ('KI', 'Kisii'), ('ND', 'Nyandarua'), ('KR', 'Karen'), ('WT', 'Watamu'), ('LI', 'Kilimani'), ('NR', 'Narok'), ('NU', 'Nyanyuki'), ('EL', 'Eldoret'), ('RU', 'Ruiru'), ('KN', 'Kinoo'), ('SU', 'Kahawa Sukari'), ('JJ', 'Juja'), ('KU', 'Kikuyu'), ('MW', 'Msambweni'), ('KA', 'Kajiado'), ('NV', 'Naivasha'), ('BU', 'Bungoma'), ('NH', 'Nyahururu'), ('LE', 'Kileleshwa'), ('NG', 'Namanga'), ('NA', 'Nakuru'), ('LV', 'Lavington'), ('WE', 'Westlands'), ('WS', 'Kahawa West'), ('AR', 'Athi River'), ('MC', 'Machakos'), ('SA', 'Kisauni'), ('LM', 'Limuru'), ('IS', 'Isinya'), ('KM', 'Kiambu'), ('TH', 'Kithiani'), ('KL', 'Kilifi')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('AP', 'Apartments'), ('LD', 'Land'), ('CO', 'Coworking'), ('HO', 'Homes'), ('OF', 'Offices'), ('ST', 'Studios'), ('WR', 'Warehouses'), ('SH', 'Shops')], max_length=2),
        ),
    ]
