# Generated by Django 2.1.5 on 2019-02-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190211_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('KW', 'Kwale'), ('NV', 'Naivasha'), ('NG', 'Namanga'), ('KL', 'Kilifi'), ('MC', 'Machakos'), ('MK', 'Mavoko'), ('IS', 'Isinya'), ('RU', 'Ruiru'), ('TH', 'Kithiani'), ('NA', 'Nakuru'), ('KR', 'Karen'), ('ND', 'Nyandarua'), ('NY', 'Nyamira'), ('RK', 'Ruaka'), ('LE', 'Kileleshwa'), ('LA', 'Langata'), ('DA', 'Dagoretti'), ('MW', 'Msambweni'), ('SY', 'Syokimau'), ('MV', 'Mvita'), ('OR', 'Ongata Rongai'), ('KK', 'Kakamega'), ('NU', 'Nyanyuki'), ('MS', 'Mombasa'), ('LO', 'Loresho'), ('KM', 'Kiambu'), ('WS', 'Kahawa West'), ('NR', 'Narok'), ('WN', 'Kahawa Wendani'), ('LK', 'Likoni'), ('BU', 'Bungoma'), ('KB', 'Kabete'), ('WT', 'Watamu'), ('KS', 'Kiserian'), ('KT', 'Kitengela'), ('KI', 'Kisii'), ('SU', 'Kahawa Sukari'), ('SA', 'Kisauni'), ('NL', 'Nyali'), ('EL', 'Eldoret'), ('AR', 'Athi River'), ('MA', 'Malindi'), ('KN', 'Kinoo'), ('KA', 'Kajiado'), ('LV', 'Lavington'), ('NE', 'Nyeri'), ('UK', 'Ukunda'), ('KU', 'Kikuyu'), ('NH', 'Nyahururu'), ('LM', 'Limuru'), ('LI', 'Kilimani'), ('WE', 'Westlands'), ('JJ', 'Juja')], max_length=2),
        ),
    ]
