# Generated by Django 2.1.5 on 2019-02-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190211_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('WN', 'Kahawa Wendani'), ('WS', 'Kahawa West'), ('KB', 'Kabete'), ('BU', 'Bungoma'), ('OR', 'Ongata Rongai'), ('KR', 'Karen'), ('JJ', 'Juja'), ('NU', 'Nyanyuki'), ('MS', 'Mombasa'), ('MC', 'Machakos'), ('SU', 'Kahawa Sukari'), ('LI', 'Kilimani'), ('KA', 'Kajiado'), ('LO', 'Loresho'), ('LM', 'Limuru'), ('MV', 'Mvita'), ('MW', 'Msambweni'), ('EL', 'Eldoret'), ('NV', 'Naivasha'), ('KI', 'Kisii'), ('NR', 'Narok'), ('NG', 'Namanga'), ('KL', 'Kilifi'), ('LE', 'Kileleshwa'), ('NA', 'Nakuru'), ('AR', 'Athi River'), ('NE', 'Nyeri'), ('KM', 'Kiambu'), ('LK', 'Likoni'), ('LA', 'Langata'), ('SY', 'Syokimau'), ('WE', 'Westlands'), ('MA', 'Malindi'), ('KK', 'Kakamega'), ('NH', 'Nyahururu'), ('ND', 'Nyandarua'), ('KN', 'Kinoo'), ('WT', 'Watamu'), ('KT', 'Kitengela'), ('NY', 'Nyamira'), ('UK', 'Ukunda'), ('SA', 'Kisauni'), ('RK', 'Ruaka'), ('TH', 'Kithiani'), ('NL', 'Nyali'), ('KW', 'Kwale'), ('LV', 'Lavington'), ('MK', 'Mavoko'), ('IS', 'Isinya'), ('KS', 'Kiserian'), ('DA', 'Dagoretti'), ('RU', 'Ruiru'), ('KU', 'Kikuyu')], max_length=2),
        ),
    ]
