# Generated by Django 2.1.5 on 2019-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20190218_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('DA', 'Dagoretti'), ('NV', 'Naivasha'), ('KS', 'Kiserian'), ('KW', 'Kwale'), ('LK', 'Likoni'), ('LM', 'Limuru'), ('MW', 'Msambweni'), ('KL', 'Kilifi'), ('KA', 'Kajiado'), ('LO', 'Loresho'), ('NA', 'Nakuru'), ('RK', 'Ruaka'), ('MV', 'Mvita'), ('KI', 'Kisii'), ('MC', 'Machakos'), ('LV', 'Lavington'), ('NL', 'Nyali'), ('MA', 'Malindi'), ('NU', 'Nyanyuki'), ('NH', 'Nyahururu'), ('KU', 'Kikuyu'), ('SY', 'Syokimau'), ('KB', 'Kabete'), ('ND', 'Nyandarua'), ('WS', 'Kahawa West'), ('KN', 'Kinoo'), ('NE', 'Nyeri'), ('NY', 'Nyamira'), ('WE', 'Westlands'), ('IS', 'Isinya'), ('MS', 'Mombasa'), ('RU', 'Ruiru'), ('KK', 'Kakamega'), ('NG', 'Namanga'), ('NR', 'Narok'), ('WT', 'Watamu'), ('WN', 'Kahawa Wendani'), ('OR', 'Ongata Rongai'), ('JJ', 'Juja'), ('SA', 'Kisauni'), ('LI', 'Kilimani'), ('UK', 'Ukunda'), ('EL', 'Eldoret'), ('KM', 'Kiambu'), ('KT', 'Kitengela'), ('SU', 'Kahawa Sukari'), ('KR', 'Karen'), ('AR', 'Athi River'), ('BU', 'Bungoma'), ('LE', 'Kileleshwa'), ('MK', 'Mavoko'), ('LA', 'Langata'), ('TH', 'Kithiani')], max_length=2),
        ),
    ]
