# Generated by Django 2.1.5 on 2019-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20190221_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('KR', 'Karen'), ('LO', 'Loresho'), ('KM', 'Kiambu'), ('KB', 'Kabete'), ('LK', 'Likoni'), ('BU', 'Bungoma'), ('RK', 'Ruaka'), ('KU', 'Kikuyu'), ('MK', 'Mavoko'), ('LM', 'Limuru'), ('MC', 'Machakos'), ('LE', 'Kileleshwa'), ('NG', 'Namanga'), ('KS', 'Kiserian'), ('MV', 'Mvita'), ('IS', 'Isinya'), ('DA', 'Dagoretti'), ('KI', 'Kisii'), ('KK', 'Kakamega'), ('NU', 'Nyanyuki'), ('ND', 'Nyandarua'), ('LI', 'Kilimani'), ('KN', 'Kinoo'), ('WS', 'Kahawa West'), ('LA', 'Langata'), ('KW', 'Kwale'), ('NL', 'Nyali'), ('SY', 'Syokimau'), ('NV', 'Naivasha'), ('RU', 'Ruiru'), ('WE', 'Westlands'), ('NE', 'Nyeri'), ('SU', 'Kahawa Sukari'), ('WN', 'Kahawa Wendani'), ('LV', 'Lavington'), ('NY', 'Nyamira'), ('MW', 'Msambweni'), ('NH', 'Nyahururu'), ('UK', 'Ukunda'), ('KA', 'Kajiado'), ('WT', 'Watamu'), ('NA', 'Nakuru'), ('OR', 'Ongata Rongai'), ('EL', 'Eldoret'), ('KT', 'Kitengela'), ('TH', 'Kithiani'), ('SA', 'Kisauni'), ('KL', 'Kilifi'), ('MA', 'Malindi'), ('JJ', 'Juja'), ('AR', 'Athi River'), ('MS', 'Mombasa'), ('NR', 'Narok')], max_length=2),
        ),
    ]
