# Generated by Django 2.1.5 on 2019-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20190221_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_favourite',
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('KM', 'Kiambu'), ('MW', 'Msambweni'), ('NV', 'Naivasha'), ('KL', 'Kilifi'), ('EL', 'Eldoret'), ('WS', 'Kahawa West'), ('KR', 'Karen'), ('OR', 'Ongata Rongai'), ('IS', 'Isinya'), ('KT', 'Kitengela'), ('MA', 'Malindi'), ('LE', 'Kileleshwa'), ('RU', 'Ruiru'), ('NL', 'Nyali'), ('RK', 'Ruaka'), ('SA', 'Kisauni'), ('KI', 'Kisii'), ('KA', 'Kajiado'), ('WN', 'Kahawa Wendani'), ('KS', 'Kiserian'), ('KW', 'Kwale'), ('SY', 'Syokimau'), ('NR', 'Narok'), ('LO', 'Loresho'), ('UK', 'Ukunda'), ('JJ', 'Juja'), ('KK', 'Kakamega'), ('NY', 'Nyamira'), ('SU', 'Kahawa Sukari'), ('NA', 'Nakuru'), ('NU', 'Nyanyuki'), ('WT', 'Watamu'), ('LI', 'Kilimani'), ('KB', 'Kabete'), ('WE', 'Westlands'), ('LA', 'Langata'), ('NE', 'Nyeri'), ('AR', 'Athi River'), ('KN', 'Kinoo'), ('MC', 'Machakos'), ('MS', 'Mombasa'), ('DA', 'Dagoretti'), ('TH', 'Kithiani'), ('MV', 'Mvita'), ('NG', 'Namanga'), ('BU', 'Bungoma'), ('LV', 'Lavington'), ('KU', 'Kikuyu'), ('MK', 'Mavoko'), ('LK', 'Likoni'), ('ND', 'Nyandarua'), ('NH', 'Nyahururu'), ('LM', 'Limuru')], max_length=2),
        ),
    ]
