# Generated by Django 2.1.5 on 2019-02-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20190221_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('KB', 'Kabete'), ('NH', 'Nyahururu'), ('DA', 'Dagoretti'), ('EL', 'Eldoret'), ('KW', 'Kwale'), ('KK', 'Kakamega'), ('JJ', 'Juja'), ('NY', 'Nyamira'), ('LA', 'Langata'), ('BU', 'Bungoma'), ('ND', 'Nyandarua'), ('AR', 'Athi River'), ('MW', 'Msambweni'), ('NR', 'Narok'), ('KI', 'Kisii'), ('KR', 'Karen'), ('KT', 'Kitengela'), ('KA', 'Kajiado'), ('LV', 'Lavington'), ('MC', 'Machakos'), ('TH', 'Kithiani'), ('KL', 'Kilifi'), ('RU', 'Ruiru'), ('SA', 'Kisauni'), ('KU', 'Kikuyu'), ('MS', 'Mombasa'), ('WN', 'Kahawa Wendani'), ('OR', 'Ongata Rongai'), ('NE', 'Nyeri'), ('RK', 'Ruaka'), ('LO', 'Loresho'), ('LM', 'Limuru'), ('NL', 'Nyali'), ('LE', 'Kileleshwa'), ('MK', 'Mavoko'), ('SY', 'Syokimau'), ('LI', 'Kilimani'), ('NA', 'Nakuru'), ('NG', 'Namanga'), ('NV', 'Naivasha'), ('WS', 'Kahawa West'), ('LK', 'Likoni'), ('KN', 'Kinoo'), ('WT', 'Watamu'), ('KS', 'Kiserian'), ('MV', 'Mvita'), ('SU', 'Kahawa Sukari'), ('KM', 'Kiambu'), ('IS', 'Isinya'), ('UK', 'Ukunda'), ('NU', 'Nyanyuki'), ('WE', 'Westlands'), ('MA', 'Malindi')], max_length=2),
        ),
    ]
