# Generated by Django 2.1.5 on 2019-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20190221_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('NY', 'Nyamira'), ('LK', 'Likoni'), ('MV', 'Mvita'), ('KK', 'Kakamega'), ('EL', 'Eldoret'), ('IS', 'Isinya'), ('NV', 'Naivasha'), ('UK', 'Ukunda'), ('LE', 'Kileleshwa'), ('NR', 'Narok'), ('TH', 'Kithiani'), ('RU', 'Ruiru'), ('NE', 'Nyeri'), ('ND', 'Nyandarua'), ('LI', 'Kilimani'), ('KW', 'Kwale'), ('MK', 'Mavoko'), ('WE', 'Westlands'), ('KM', 'Kiambu'), ('AR', 'Athi River'), ('NA', 'Nakuru'), ('MS', 'Mombasa'), ('KR', 'Karen'), ('JJ', 'Juja'), ('SA', 'Kisauni'), ('KS', 'Kiserian'), ('DA', 'Dagoretti'), ('NL', 'Nyali'), ('KI', 'Kisii'), ('SU', 'Kahawa Sukari'), ('NG', 'Namanga'), ('KU', 'Kikuyu'), ('RK', 'Ruaka'), ('NH', 'Nyahururu'), ('LV', 'Lavington'), ('KN', 'Kinoo'), ('KA', 'Kajiado'), ('KL', 'Kilifi'), ('NU', 'Nyanyuki'), ('MC', 'Machakos'), ('LO', 'Loresho'), ('WN', 'Kahawa Wendani'), ('KT', 'Kitengela'), ('BU', 'Bungoma'), ('WT', 'Watamu'), ('OR', 'Ongata Rongai'), ('WS', 'Kahawa West'), ('MW', 'Msambweni'), ('KB', 'Kabete'), ('LM', 'Limuru'), ('SY', 'Syokimau'), ('LA', 'Langata'), ('MA', 'Malindi')], max_length=2),
        ),
    ]
