# Generated by Django 2.1.5 on 2019-02-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20190221_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('TH', 'Kithiani'), ('KU', 'Kikuyu'), ('WN', 'Kahawa Wendani'), ('MW', 'Msambweni'), ('NU', 'Nyanyuki'), ('MA', 'Malindi'), ('NE', 'Nyeri'), ('MK', 'Mavoko'), ('KM', 'Kiambu'), ('MV', 'Mvita'), ('IS', 'Isinya'), ('WS', 'Kahawa West'), ('KR', 'Karen'), ('NR', 'Narok'), ('LE', 'Kileleshwa'), ('KA', 'Kajiado'), ('KT', 'Kitengela'), ('KL', 'Kilifi'), ('NV', 'Naivasha'), ('NG', 'Namanga'), ('DA', 'Dagoretti'), ('RU', 'Ruiru'), ('KW', 'Kwale'), ('MC', 'Machakos'), ('SU', 'Kahawa Sukari'), ('NA', 'Nakuru'), ('KB', 'Kabete'), ('KI', 'Kisii'), ('LK', 'Likoni'), ('MS', 'Mombasa'), ('OR', 'Ongata Rongai'), ('LM', 'Limuru'), ('LV', 'Lavington'), ('WE', 'Westlands'), ('SY', 'Syokimau'), ('LI', 'Kilimani'), ('KK', 'Kakamega'), ('LO', 'Loresho'), ('RK', 'Ruaka'), ('NY', 'Nyamira'), ('NL', 'Nyali'), ('EL', 'Eldoret'), ('UK', 'Ukunda'), ('LA', 'Langata'), ('JJ', 'Juja'), ('SA', 'Kisauni'), ('ND', 'Nyandarua'), ('BU', 'Bungoma'), ('WT', 'Watamu'), ('NH', 'Nyahururu'), ('KN', 'Kinoo'), ('AR', 'Athi River'), ('KS', 'Kiserian')], max_length=2),
        ),
    ]
