# Generated by Django 2.1.5 on 2019-02-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20190221_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('WN', 'Kahawa Wendani'), ('KK', 'Kakamega'), ('OR', 'Ongata Rongai'), ('KS', 'Kiserian'), ('NH', 'Nyahururu'), ('WE', 'Westlands'), ('KN', 'Kinoo'), ('UK', 'Ukunda'), ('NG', 'Namanga'), ('JJ', 'Juja'), ('NY', 'Nyamira'), ('KU', 'Kikuyu'), ('ND', 'Nyandarua'), ('WT', 'Watamu'), ('RU', 'Ruiru'), ('NR', 'Narok'), ('TH', 'Kithiani'), ('DA', 'Dagoretti'), ('LE', 'Kileleshwa'), ('NA', 'Nakuru'), ('AR', 'Athi River'), ('KM', 'Kiambu'), ('LI', 'Kilimani'), ('LK', 'Likoni'), ('MV', 'Mvita'), ('KR', 'Karen'), ('MW', 'Msambweni'), ('NV', 'Naivasha'), ('MA', 'Malindi'), ('KB', 'Kabete'), ('NL', 'Nyali'), ('MC', 'Machakos'), ('NE', 'Nyeri'), ('KT', 'Kitengela'), ('KI', 'Kisii'), ('NU', 'Nyanyuki'), ('LA', 'Langata'), ('RK', 'Ruaka'), ('LM', 'Limuru'), ('IS', 'Isinya'), ('LO', 'Loresho'), ('MS', 'Mombasa'), ('KA', 'Kajiado'), ('EL', 'Eldoret'), ('SY', 'Syokimau'), ('KW', 'Kwale'), ('WS', 'Kahawa West'), ('KL', 'Kilifi'), ('LV', 'Lavington'), ('BU', 'Bungoma'), ('SU', 'Kahawa Sukari'), ('MK', 'Mavoko'), ('SA', 'Kisauni')], max_length=2),
        ),
    ]
