# Generated by Django 2.1.5 on 2019-02-26 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0017_auto_20190221_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('KK', 'Kakamega'), ('KI', 'Kisii'), ('JJ', 'Juja'), ('NG', 'Namanga'), ('LE', 'Kileleshwa'), ('RU', 'Ruiru'), ('UK', 'Ukunda'), ('TH', 'Kithiani'), ('WN', 'Kahawa Wendani'), ('AR', 'Athi River'), ('NY', 'Nyamira'), ('LI', 'Kilimani'), ('SU', 'Kahawa Sukari'), ('KA', 'Kajiado'), ('EL', 'Eldoret'), ('MK', 'Mavoko'), ('KS', 'Kiserian'), ('SA', 'Kisauni'), ('MW', 'Msambweni'), ('MC', 'Machakos'), ('OR', 'Ongata Rongai'), ('LO', 'Loresho'), ('LK', 'Likoni'), ('WS', 'Kahawa West'), ('NR', 'Narok'), ('KR', 'Karen'), ('DA', 'Dagoretti'), ('MA', 'Malindi'), ('KN', 'Kinoo'), ('LM', 'Limuru'), ('SY', 'Syokimau'), ('WE', 'Westlands'), ('MS', 'Mombasa'), ('ND', 'Nyandarua'), ('RK', 'Ruaka'), ('NL', 'Nyali'), ('KW', 'Kwale'), ('MV', 'Mvita'), ('KB', 'Kabete'), ('BU', 'Bungoma'), ('NH', 'Nyahururu'), ('KM', 'Kiambu'), ('KT', 'Kitengela'), ('WT', 'Watamu'), ('NU', 'Nyanyuki'), ('NV', 'Naivasha'), ('LV', 'Lavington'), ('KL', 'Kilifi'), ('NE', 'Nyeri'), ('LA', 'Langata'), ('IS', 'Isinya'), ('NA', 'Nakuru'), ('KU', 'Kikuyu')], max_length=2),
        ),
        migrations.AddField(
            model_name='reviews',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Listing'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
