# Generated by Django 2.1.5 on 2019-03-01 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0019_auto_20190226_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('MS', 'Mombasa'), ('BU', 'Bungoma'), ('NG', 'Namanga'), ('RU', 'Ruiru'), ('WT', 'Watamu'), ('KK', 'Kakamega'), ('MC', 'Machakos'), ('LA', 'Langata'), ('KU', 'Kikuyu'), ('KN', 'Kinoo'), ('LE', 'Kileleshwa'), ('UK', 'Ukunda'), ('NL', 'Nyali'), ('SY', 'Syokimau'), ('NA', 'Nakuru'), ('WN', 'Kahawa Wendani'), ('LO', 'Loresho'), ('KL', 'Kilifi'), ('SU', 'Kahawa Sukari'), ('NH', 'Nyahururu'), ('KR', 'Karen'), ('OR', 'Ongata Rongai'), ('MV', 'Mvita'), ('EL', 'Eldoret'), ('LK', 'Likoni'), ('KA', 'Kajiado'), ('SA', 'Kisauni'), ('ND', 'Nyandarua'), ('LI', 'Kilimani'), ('DA', 'Dagoretti'), ('AR', 'Athi River'), ('NE', 'Nyeri'), ('MA', 'Malindi'), ('WE', 'Westlands'), ('LM', 'Limuru'), ('KB', 'Kabete'), ('RK', 'Ruaka'), ('KI', 'Kisii'), ('KM', 'Kiambu'), ('WS', 'Kahawa West'), ('KT', 'Kitengela'), ('NY', 'Nyamira'), ('MW', 'Msambweni'), ('IS', 'Isinya'), ('JJ', 'Juja'), ('KS', 'Kiserian'), ('LV', 'Lavington'), ('NU', 'Nyanyuki'), ('TH', 'Kithiani'), ('NV', 'Naivasha'), ('KW', 'Kwale'), ('MK', 'Mavoko'), ('NR', 'Narok')], max_length=2),
        ),
    ]
