# Generated by Django 2.1.5 on 2019-03-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20190302_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('KU', 'Kikuyu'), ('NG', 'Namanga'), ('WS', 'Kahawa West'), ('NR', 'Narok'), ('TH', 'Kithiani'), ('KK', 'Kakamega'), ('SY', 'Syokimau'), ('AR', 'Athi River'), ('KW', 'Kwale'), ('NE', 'Nyeri'), ('MV', 'Mvita'), ('IS', 'Isinya'), ('RK', 'Ruaka'), ('ND', 'Nyandarua'), ('KL', 'Kilifi'), ('LE', 'Kileleshwa'), ('KI', 'Kisii'), ('MC', 'Machakos'), ('WN', 'Kahawa Wendani'), ('WE', 'Westlands'), ('LK', 'Likoni'), ('LO', 'Loresho'), ('KR', 'Karen'), ('LI', 'Kilimani'), ('RU', 'Ruiru'), ('KS', 'Kiserian'), ('EL', 'Eldoret'), ('LM', 'Limuru'), ('NU', 'Nyanyuki'), ('SU', 'Kahawa Sukari'), ('LV', 'Lavington'), ('LA', 'Langata'), ('NH', 'Nyahururu'), ('UK', 'Ukunda'), ('KN', 'Kinoo'), ('DA', 'Dagoretti'), ('SA', 'Kisauni'), ('MS', 'Mombasa'), ('WT', 'Watamu'), ('KB', 'Kabete'), ('MK', 'Mavoko'), ('OR', 'Ongata Rongai'), ('MW', 'Msambweni'), ('NV', 'Naivasha'), ('BU', 'Bungoma'), ('JJ', 'Juja'), ('MA', 'Malindi'), ('NL', 'Nyali'), ('NA', 'Nakuru'), ('NY', 'Nyamira'), ('KM', 'Kiambu'), ('KT', 'Kitengela'), ('KA', 'Kajiado')], max_length=2),
        ),
    ]
