# Generated by Django 2.1.5 on 2019-03-03 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20190302_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('LO', 'Loresho'), ('KL', 'Kilifi'), ('LA', 'Langata'), ('NL', 'Nyali'), ('NV', 'Naivasha'), ('MC', 'Machakos'), ('IS', 'Isinya'), ('KB', 'Kabete'), ('NY', 'Nyamira'), ('MK', 'Mavoko'), ('UK', 'Ukunda'), ('WS', 'Kahawa West'), ('KU', 'Kikuyu'), ('NU', 'Nyanyuki'), ('KA', 'Kajiado'), ('LE', 'Kileleshwa'), ('RU', 'Ruiru'), ('NA', 'Nakuru'), ('WT', 'Watamu'), ('TH', 'Kithiani'), ('SA', 'Kisauni'), ('RK', 'Ruaka'), ('ND', 'Nyandarua'), ('MS', 'Mombasa'), ('KI', 'Kisii'), ('SY', 'Syokimau'), ('JJ', 'Juja'), ('LM', 'Limuru'), ('AR', 'Athi River'), ('DA', 'Dagoretti'), ('KS', 'Kiserian'), ('LI', 'Kilimani'), ('KN', 'Kinoo'), ('WN', 'Kahawa Wendani'), ('KT', 'Kitengela'), ('OR', 'Ongata Rongai'), ('MV', 'Mvita'), ('BU', 'Bungoma'), ('WE', 'Westlands'), ('NG', 'Namanga'), ('LK', 'Likoni'), ('MA', 'Malindi'), ('MW', 'Msambweni'), ('LV', 'Lavington'), ('KR', 'Karen'), ('NH', 'Nyahururu'), ('NE', 'Nyeri'), ('KM', 'Kiambu'), ('KK', 'Kakamega'), ('NR', 'Narok'), ('SU', 'Kahawa Sukari'), ('KW', 'Kwale'), ('EL', 'Eldoret')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='billing',
            field=models.CharField(blank=True, choices=[('HR', 'Hour'), ('DY', 'Day'), ('MT', 'Month'), ('WK', 'Week'), ('DK', 'Desk'), ('NT', 'Night')], max_length=200),
        ),
    ]
