# Generated by Django 2.1.5 on 2019-03-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20190302_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='availability',
            new_name='is_availability',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('KI', 'Kisii'), ('NE', 'Nyeri'), ('OR', 'Ongata Rongai'), ('MS', 'Mombasa'), ('SY', 'Syokimau'), ('MC', 'Machakos'), ('MK', 'Mavoko'), ('AR', 'Athi River'), ('SU', 'Kahawa Sukari'), ('BU', 'Bungoma'), ('MA', 'Malindi'), ('WE', 'Westlands'), ('KS', 'Kiserian'), ('UK', 'Ukunda'), ('KB', 'Kabete'), ('DA', 'Dagoretti'), ('MW', 'Msambweni'), ('IS', 'Isinya'), ('NR', 'Narok'), ('WN', 'Kahawa Wendani'), ('NG', 'Namanga'), ('NH', 'Nyahururu'), ('KU', 'Kikuyu'), ('EL', 'Eldoret'), ('KT', 'Kitengela'), ('KK', 'Kakamega'), ('KM', 'Kiambu'), ('NL', 'Nyali'), ('LM', 'Limuru'), ('TH', 'Kithiani'), ('MV', 'Mvita'), ('KA', 'Kajiado'), ('KW', 'Kwale'), ('LE', 'Kileleshwa'), ('NA', 'Nakuru'), ('LO', 'Loresho'), ('NY', 'Nyamira'), ('KL', 'Kilifi'), ('KR', 'Karen'), ('LA', 'Langata'), ('SA', 'Kisauni'), ('ND', 'Nyandarua'), ('LI', 'Kilimani'), ('LK', 'Likoni'), ('RK', 'Ruaka'), ('JJ', 'Juja'), ('LV', 'Lavington'), ('WT', 'Watamu'), ('NV', 'Naivasha'), ('NU', 'Nyanyuki'), ('RU', 'Ruiru'), ('WS', 'Kahawa West'), ('KN', 'Kinoo')], max_length=2),
        ),
    ]
