# Generated by Django 2.1.5 on 2019-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_auto_20190304_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('LI', 'Kilimani'), ('SA', 'Kisauni'), ('UK', 'Ukunda'), ('OR', 'Ongata Rongai'), ('NY', 'Nyamira'), ('JJ', 'Juja'), ('LM', 'Limuru'), ('IS', 'Isinya'), ('LO', 'Loresho'), ('LE', 'Kileleshwa'), ('MV', 'Mvita'), ('NE', 'Nyeri'), ('DA', 'Dagoretti'), ('NL', 'Nyali'), ('MK', 'Mavoko'), ('KI', 'Kisii'), ('NU', 'Nyanyuki'), ('ND', 'Nyandarua'), ('MC', 'Machakos'), ('KR', 'Karen'), ('KL', 'Kilifi'), ('RU', 'Ruiru'), ('KB', 'Kabete'), ('NA', 'Nakuru'), ('WE', 'Westlands'), ('KT', 'Kitengela'), ('BU', 'Bungoma'), ('KN', 'Kinoo'), ('NV', 'Naivasha'), ('WS', 'Kahawa West'), ('RK', 'Ruaka'), ('MS', 'Mombasa'), ('KU', 'Kikuyu'), ('AR', 'Athi River'), ('NH', 'Nyahururu'), ('NG', 'Namanga'), ('LA', 'Langata'), ('KK', 'Kakamega'), ('EL', 'Eldoret'), ('SU', 'Kahawa Sukari'), ('KA', 'Kajiado'), ('KS', 'Kiserian'), ('TH', 'Kithiani'), ('MW', 'Msambweni'), ('LK', 'Likoni'), ('NR', 'Narok'), ('LV', 'Lavington'), ('SY', 'Syokimau'), ('MA', 'Malindi'), ('WT', 'Watamu'), ('KM', 'Kiambu'), ('KW', 'Kwale'), ('WN', 'Kahawa Wendani')], max_length=2),
        ),
    ]
