# Generated by Django 2.1.5 on 2019-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_auto_20190304_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('WN', 'Kahawa Wendani'), ('RU', 'Ruiru'), ('KB', 'Kabete'), ('WE', 'Westlands'), ('KS', 'Kiserian'), ('NE', 'Nyeri'), ('JJ', 'Juja'), ('IS', 'Isinya'), ('KU', 'Kikuyu'), ('SA', 'Kisauni'), ('LA', 'Langata'), ('NV', 'Naivasha'), ('WT', 'Watamu'), ('SU', 'Kahawa Sukari'), ('OR', 'Ongata Rongai'), ('KT', 'Kitengela'), ('NU', 'Nyanyuki'), ('NR', 'Narok'), ('KL', 'Kilifi'), ('KK', 'Kakamega'), ('SY', 'Syokimau'), ('MC', 'Machakos'), ('KW', 'Kwale'), ('LE', 'Kileleshwa'), ('LO', 'Loresho'), ('WS', 'Kahawa West'), ('MV', 'Mvita'), ('MW', 'Msambweni'), ('MA', 'Malindi'), ('MS', 'Mombasa'), ('KA', 'Kajiado'), ('NA', 'Nakuru'), ('DA', 'Dagoretti'), ('ND', 'Nyandarua'), ('NG', 'Namanga'), ('NL', 'Nyali'), ('KN', 'Kinoo'), ('LM', 'Limuru'), ('NY', 'Nyamira'), ('LK', 'Likoni'), ('UK', 'Ukunda'), ('MK', 'Mavoko'), ('EL', 'Eldoret'), ('LI', 'Kilimani'), ('BU', 'Bungoma'), ('KI', 'Kisii'), ('NH', 'Nyahururu'), ('KM', 'Kiambu'), ('LV', 'Lavington'), ('KR', 'Karen'), ('TH', 'Kithiani'), ('RK', 'Ruaka'), ('AR', 'Athi River')], max_length=2),
        ),
    ]
