# Generated by Django 2.1.5 on 2019-03-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_auto_20190304_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('KK', 'Kakamega'), ('KB', 'Kabete'), ('KM', 'Kiambu'), ('NA', 'Nakuru'), ('ND', 'Nyandarua'), ('MW', 'Msambweni'), ('LO', 'Loresho'), ('BU', 'Bungoma'), ('MC', 'Machakos'), ('KU', 'Kikuyu'), ('KI', 'Kisii'), ('LK', 'Likoni'), ('LA', 'Langata'), ('NR', 'Narok'), ('WT', 'Watamu'), ('LM', 'Limuru'), ('IS', 'Isinya'), ('SA', 'Kisauni'), ('MS', 'Mombasa'), ('EL', 'Eldoret'), ('LI', 'Kilimani'), ('KW', 'Kwale'), ('KT', 'Kitengela'), ('AR', 'Athi River'), ('KS', 'Kiserian'), ('KN', 'Kinoo'), ('SU', 'Kahawa Sukari'), ('DA', 'Dagoretti'), ('NE', 'Nyeri'), ('WS', 'Kahawa West'), ('OR', 'Ongata Rongai'), ('RU', 'Ruiru'), ('NG', 'Namanga'), ('RK', 'Ruaka'), ('NY', 'Nyamira'), ('LE', 'Kileleshwa'), ('MK', 'Mavoko'), ('NU', 'Nyanyuki'), ('LV', 'Lavington'), ('NV', 'Naivasha'), ('KL', 'Kilifi'), ('MV', 'Mvita'), ('KR', 'Karen'), ('WE', 'Westlands'), ('KA', 'Kajiado'), ('NH', 'Nyahururu'), ('WN', 'Kahawa Wendani'), ('JJ', 'Juja'), ('NL', 'Nyali'), ('UK', 'Ukunda'), ('MA', 'Malindi'), ('TH', 'Kithiani'), ('SY', 'Syokimau')], max_length=2),
        ),
    ]
