# Generated by Django 2.1.5 on 2019-03-06 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_auto_20190304_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('WN', 'Kahawa Wendani'), ('KM', 'Kiambu'), ('IS', 'Isinya'), ('LV', 'Lavington'), ('NV', 'Naivasha'), ('EL', 'Eldoret'), ('TH', 'Kithiani'), ('LK', 'Likoni'), ('KA', 'Kajiado'), ('OR', 'Ongata Rongai'), ('LI', 'Kilimani'), ('WE', 'Westlands'), ('LE', 'Kileleshwa'), ('RU', 'Ruiru'), ('NH', 'Nyahururu'), ('ND', 'Nyandarua'), ('JJ', 'Juja'), ('WS', 'Kahawa West'), ('KK', 'Kakamega'), ('LO', 'Loresho'), ('WT', 'Watamu'), ('MA', 'Malindi'), ('NG', 'Namanga'), ('SU', 'Kahawa Sukari'), ('KI', 'Kisii'), ('LM', 'Limuru'), ('MW', 'Msambweni'), ('NA', 'Nakuru'), ('KL', 'Kilifi'), ('NE', 'Nyeri'), ('KU', 'Kikuyu'), ('KR', 'Karen'), ('KS', 'Kiserian'), ('LA', 'Langata'), ('KW', 'Kwale'), ('NU', 'Nyanyuki'), ('NY', 'Nyamira'), ('SY', 'Syokimau'), ('KT', 'Kitengela'), ('NR', 'Narok'), ('BU', 'Bungoma'), ('RK', 'Ruaka'), ('MC', 'Machakos'), ('SA', 'Kisauni'), ('DA', 'Dagoretti'), ('NL', 'Nyali'), ('UK', 'Ukunda'), ('KN', 'Kinoo'), ('KB', 'Kabete'), ('MK', 'Mavoko'), ('MV', 'Mvita'), ('MS', 'Mombasa'), ('AR', 'Athi River')], max_length=2),
        ),
    ]
