# Generated by Django 2.1.5 on 2019-03-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20190305_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('KR', 'Karen'), ('EL', 'Eldoret'), ('DA', 'Dagoretti'), ('WT', 'Watamu'), ('LV', 'Lavington'), ('KT', 'Kitengela'), ('SA', 'Kisauni'), ('KU', 'Kikuyu'), ('SU', 'Kahawa Sukari'), ('LM', 'Limuru'), ('IS', 'Isinya'), ('LO', 'Loresho'), ('NR', 'Narok'), ('BU', 'Bungoma'), ('KL', 'Kilifi'), ('NL', 'Nyali'), ('KN', 'Kinoo'), ('RK', 'Ruaka'), ('OR', 'Ongata Rongai'), ('KA', 'Kajiado'), ('LE', 'Kileleshwa'), ('MW', 'Msambweni'), ('UK', 'Ukunda'), ('ND', 'Nyandarua'), ('NG', 'Namanga'), ('NY', 'Nyamira'), ('MK', 'Mavoko'), ('LK', 'Likoni'), ('KS', 'Kiserian'), ('LI', 'Kilimani'), ('TH', 'Kithiani'), ('MA', 'Malindi'), ('SY', 'Syokimau'), ('KI', 'Kisii'), ('AR', 'Athi River'), ('MC', 'Machakos'), ('MV', 'Mvita'), ('NU', 'Nyanyuki'), ('WS', 'Kahawa West'), ('KK', 'Kakamega'), ('RU', 'Ruiru'), ('NE', 'Nyeri'), ('WN', 'Kahawa Wendani'), ('MS', 'Mombasa'), ('NV', 'Naivasha'), ('LA', 'Langata'), ('KB', 'Kabete'), ('JJ', 'Juja'), ('WE', 'Westlands'), ('NA', 'Nakuru'), ('KM', 'Kiambu'), ('NH', 'Nyahururu'), ('KW', 'Kwale')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='billing',
            field=models.CharField(blank=True, choices=[('HR', 'Hour'), ('DY', 'Day'), ('MT', 'Month'), ('WK', 'Week'), ('DK', 'Desk'), ('NT', 'Night'), ('PE', 'Person')], max_length=200),
        ),
    ]
