# Generated by Django 2.1.5 on 2019-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_auto_20190306_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='used_for',
            field=models.CharField(choices=[('AC', 'Accommodation & Housing'), ('SH', 'Shopping'), ('FO', 'Food & Drink'), ('FU', 'Fun & Experiences'), ('WE', 'Health & Wellness'), ('PA', 'Parking'), ('NL', 'Nightlife'), ('SE', 'Social Events'), ('CE', 'Corporate Events'), ('WE', 'Weddings'), ('RE', 'Retail Shops'), ('CA', 'Camping'), ('TR', 'Travel & Hospitality')], default='Other', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('OR', 'Ongata Rongai'), ('LK', 'Likoni'), ('NA', 'Nakuru'), ('NU', 'Nyanyuki'), ('MK', 'Mavoko'), ('LI', 'Kilimani'), ('KU', 'Kikuyu'), ('MV', 'Mvita'), ('SY', 'Syokimau'), ('KT', 'Kitengela'), ('KW', 'Kwale'), ('LA', 'Langata'), ('BU', 'Bungoma'), ('NR', 'Narok'), ('MW', 'Msambweni'), ('WE', 'Westlands'), ('IS', 'Isinya'), ('NV', 'Naivasha'), ('MA', 'Malindi'), ('MC', 'Machakos'), ('KI', 'Kisii'), ('NY', 'Nyamira'), ('DA', 'Dagoretti'), ('ND', 'Nyandarua'), ('KL', 'Kilifi'), ('KN', 'Kinoo'), ('SU', 'Kahawa Sukari'), ('SA', 'Kisauni'), ('LE', 'Kileleshwa'), ('WS', 'Kahawa West'), ('LO', 'Loresho'), ('KK', 'Kakamega'), ('NE', 'Nyeri'), ('KR', 'Karen'), ('RK', 'Ruaka'), ('JJ', 'Juja'), ('LM', 'Limuru'), ('WN', 'Kahawa Wendani'), ('RU', 'Ruiru'), ('KM', 'Kiambu'), ('TH', 'Kithiani'), ('AR', 'Athi River'), ('NL', 'Nyali'), ('WT', 'Watamu'), ('KS', 'Kiserian'), ('UK', 'Ukunda'), ('NG', 'Namanga'), ('KB', 'Kabete'), ('LV', 'Lavington'), ('NH', 'Nyahururu'), ('MS', 'Mombasa'), ('KA', 'Kajiado'), ('EL', 'Eldoret')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('HT', 'Hotels'), ('RT', 'Restaurants'), ('RE', 'Resorts'), ('SP', 'Spa'), ('GY', 'Gym'), ('AP', 'Apartments'), ('LD', 'Land'), ('CO', 'Coworking'), ('HO', 'Homes'), ('OF', 'Offices'), ('ST', 'Studios'), ('WR', 'Warehouses'), ('SH', 'Shops')], max_length=2),
        ),
    ]
