# Generated by Django 2.1.5 on 2019-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_auto_20190306_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('WS', 'Kahawa West'), ('NA', 'Nakuru'), ('KT', 'Kitengela'), ('UK', 'Ukunda'), ('LE', 'Kileleshwa'), ('LA', 'Langata'), ('NL', 'Nyali'), ('NH', 'Nyahururu'), ('MS', 'Mombasa'), ('LV', 'Lavington'), ('IS', 'Isinya'), ('RK', 'Ruaka'), ('KB', 'Kabete'), ('KS', 'Kiserian'), ('NR', 'Narok'), ('KU', 'Kikuyu'), ('NE', 'Nyeri'), ('AR', 'Athi River'), ('LK', 'Likoni'), ('RU', 'Ruiru'), ('NY', 'Nyamira'), ('NG', 'Namanga'), ('KK', 'Kakamega'), ('WN', 'Kahawa Wendani'), ('MV', 'Mvita'), ('KN', 'Kinoo'), ('KR', 'Karen'), ('LM', 'Limuru'), ('MA', 'Malindi'), ('JJ', 'Juja'), ('WE', 'Westlands'), ('KL', 'Kilifi'), ('LI', 'Kilimani'), ('MC', 'Machakos'), ('NV', 'Naivasha'), ('SY', 'Syokimau'), ('SA', 'Kisauni'), ('KA', 'Kajiado'), ('LO', 'Loresho'), ('DA', 'Dagoretti'), ('KI', 'Kisii'), ('OR', 'Ongata Rongai'), ('SU', 'Kahawa Sukari'), ('KW', 'Kwale'), ('BU', 'Bungoma'), ('NU', 'Nyanyuki'), ('WT', 'Watamu'), ('ND', 'Nyandarua'), ('MW', 'Msambweni'), ('EL', 'Eldoret'), ('KM', 'Kiambu'), ('TH', 'Kithiani'), ('MK', 'Mavoko')], max_length=2),
        ),
    ]
