# Generated by Django 2.1.5 on 2019-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_auto_20190307_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('LV', 'Lavington'), ('NG', 'Namanga'), ('KA', 'Kajiado'), ('NR', 'Narok'), ('SU', 'Kahawa Sukari'), ('KU', 'Kikuyu'), ('WN', 'Kahawa Wendani'), ('LA', 'Langata'), ('LE', 'Kileleshwa'), ('KL', 'Kilifi'), ('KR', 'Karen'), ('NL', 'Nyali'), ('KS', 'Kiserian'), ('NA', 'Nakuru'), ('WS', 'Kahawa West'), ('LK', 'Likoni'), ('LM', 'Limuru'), ('MV', 'Mvita'), ('ND', 'Nyandarua'), ('LI', 'Kilimani'), ('AR', 'Athi River'), ('MS', 'Mombasa'), ('TH', 'Kithiani'), ('RU', 'Ruiru'), ('MC', 'Machakos'), ('WT', 'Watamu'), ('WE', 'Westlands'), ('MA', 'Malindi'), ('IS', 'Isinya'), ('JJ', 'Juja'), ('KT', 'Kitengela'), ('KM', 'Kiambu'), ('SA', 'Kisauni'), ('UK', 'Ukunda'), ('NV', 'Naivasha'), ('SY', 'Syokimau'), ('MK', 'Mavoko'), ('OR', 'Ongata Rongai'), ('RK', 'Ruaka'), ('LO', 'Loresho'), ('BU', 'Bungoma'), ('EL', 'Eldoret'), ('NU', 'Nyanyuki'), ('NH', 'Nyahururu'), ('KN', 'Kinoo'), ('KI', 'Kisii'), ('KK', 'Kakamega'), ('NE', 'Nyeri'), ('DA', 'Dagoretti'), ('KB', 'Kabete'), ('MW', 'Msambweni'), ('KW', 'Kwale'), ('NY', 'Nyamira')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='used_for',
            field=models.CharField(choices=[('AC', 'Accommodation & Housing'), ('SH', 'Shopping'), ('FO', 'Food & Drink'), ('FU', 'Fun & Experiences'), ('WE', 'Health & Wellness'), ('PA', 'Parking'), ('NL', 'Nightlife'), ('SE', 'Social Events'), ('CE', 'Corporate Events'), ('WD', 'Weddings'), ('RE', 'Retail Shops'), ('CA', 'Camping'), ('TR', 'Travel & Hospitality'), ('ET', 'Entertainment'), ('ME', 'MeetUps and Meetings'), ('OF', 'Office & Co-Working'), ('OT', 'Other Uses')], default='OT', max_length=200),
        ),
    ]
