# Generated by Django 2.1.5 on 2019-03-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_auto_20190307_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('RU', 'Ruiru'), ('NV', 'Naivasha'), ('KM', 'Kiambu'), ('KB', 'Kabete'), ('NR', 'Narok'), ('KA', 'Kajiado'), ('ND', 'Nyandarua'), ('WS', 'Kahawa West'), ('JJ', 'Juja'), ('KI', 'Kisii'), ('BU', 'Bungoma'), ('LA', 'Langata'), ('LM', 'Limuru'), ('KL', 'Kilifi'), ('NH', 'Nyahururu'), ('WE', 'Westlands'), ('KT', 'Kitengela'), ('MC', 'Machakos'), ('MW', 'Msambweni'), ('MK', 'Mavoko'), ('TH', 'Kithiani'), ('WN', 'Kahawa Wendani'), ('LI', 'Kilimani'), ('WT', 'Watamu'), ('MS', 'Mombasa'), ('SU', 'Kahawa Sukari'), ('IS', 'Isinya'), ('KS', 'Kiserian'), ('KW', 'Kwale'), ('UK', 'Ukunda'), ('EL', 'Eldoret'), ('AR', 'Athi River'), ('KN', 'Kinoo'), ('KK', 'Kakamega'), ('LV', 'Lavington'), ('MV', 'Mvita'), ('OR', 'Ongata Rongai'), ('NU', 'Nyanyuki'), ('NY', 'Nyamira'), ('LO', 'Loresho'), ('SA', 'Kisauni'), ('MA', 'Malindi'), ('RK', 'Ruaka'), ('LE', 'Kileleshwa'), ('KR', 'Karen'), ('NG', 'Namanga'), ('NL', 'Nyali'), ('SY', 'Syokimau'), ('NA', 'Nakuru'), ('KU', 'Kikuyu'), ('LK', 'Likoni'), ('NE', 'Nyeri'), ('DA', 'Dagoretti')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('HT', 'Hotel'), ('RT', 'Restaurant'), ('RE', 'Resort'), ('SP', 'Spa'), ('GY', 'Gym'), ('AP', 'Apartment'), ('LD', 'Land'), ('CO', 'Coworking'), ('HO', 'Homes'), ('OF', 'Offices'), ('ST', 'Studios'), ('WR', 'Warehouse'), ('SH', 'Shops'), ('VR', 'Vacation Rental'), ('PU', 'Pop Up Store')], max_length=2),
        ),
    ]
