# Generated by Django 2.1.5 on 2019-03-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_auto_20190307_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('LK', 'Likoni'), ('UK', 'Ukunda'), ('KS', 'Kiserian'), ('KR', 'Karen'), ('SA', 'Kisauni'), ('NY', 'Nyamira'), ('DA', 'Dagoretti'), ('WN', 'Kahawa Wendani'), ('LA', 'Langata'), ('KK', 'Kakamega'), ('KN', 'Kinoo'), ('NU', 'Nyanyuki'), ('NA', 'Nakuru'), ('LI', 'Kilimani'), ('LM', 'Limuru'), ('KU', 'Kikuyu'), ('KM', 'Kiambu'), ('RU', 'Ruiru'), ('EL', 'Eldoret'), ('KW', 'Kwale'), ('BU', 'Bungoma'), ('KA', 'Kajiado'), ('TH', 'Kithiani'), ('NR', 'Narok'), ('MA', 'Malindi'), ('KI', 'Kisii'), ('AR', 'Athi River'), ('KB', 'Kabete'), ('WE', 'Westlands'), ('KT', 'Kitengela'), ('NL', 'Nyali'), ('IS', 'Isinya'), ('MC', 'Machakos'), ('WT', 'Watamu'), ('MK', 'Mavoko'), ('SY', 'Syokimau'), ('NV', 'Naivasha'), ('NE', 'Nyeri'), ('SU', 'Kahawa Sukari'), ('WS', 'Kahawa West'), ('NH', 'Nyahururu'), ('JJ', 'Juja'), ('LO', 'Loresho'), ('NG', 'Namanga'), ('MW', 'Msambweni'), ('LV', 'Lavington'), ('KL', 'Kilifi'), ('RK', 'Ruaka'), ('MV', 'Mvita'), ('LE', 'Kileleshwa'), ('MS', 'Mombasa'), ('ND', 'Nyandarua'), ('OR', 'Ongata Rongai')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='used_for',
            field=models.CharField(choices=[('AC', 'Accommodation & Housing'), ('SH', 'Shopping'), ('FO', 'Food & Drink'), ('FU', 'Fun & Experiences'), ('WE', 'Health & Wellness'), ('PA', 'Parking'), ('NL', 'Nightlife'), ('SE', 'Social Events'), ('CE', 'Corporate Events'), ('WD', 'Weddings'), ('RE', 'Retail Shops'), ('CA', 'Camping'), ('TR', 'Travel & Hospitality'), ('ET', 'Entertainment'), ('ME', 'MeetUps and Meetings'), ('OF', 'Office & Co-Working'), ('ST', 'Storage'), ('OT', 'Other Uses')], default='OT', max_length=200),
        ),
    ]
