# Generated by Django 2.1.5 on 2019-03-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_auto_20190308_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('JJ', 'Juja'), ('OR', 'Ongata Rongai'), ('KU', 'Kikuyu'), ('NV', 'Naivasha'), ('KS', 'Kiserian'), ('NR', 'Narok'), ('WE', 'Westlands'), ('KA', 'Kajiado'), ('NH', 'Nyahururu'), ('SU', 'Kahawa Sukari'), ('KL', 'Kilifi'), ('NY', 'Nyamira'), ('SA', 'Kisauni'), ('WS', 'Kahawa West'), ('MC', 'Machakos'), ('LV', 'Lavington'), ('SY', 'Syokimau'), ('KB', 'Kabete'), ('NA', 'Nakuru'), ('NG', 'Namanga'), ('KK', 'Kakamega'), ('KT', 'Kitengela'), ('TH', 'Kithiani'), ('MA', 'Malindi'), ('ND', 'Nyandarua'), ('LA', 'Langata'), ('EL', 'Eldoret'), ('IS', 'Isinya'), ('UK', 'Ukunda'), ('BU', 'Bungoma'), ('MK', 'Mavoko'), ('MS', 'Mombasa'), ('MW', 'Msambweni'), ('LE', 'Kileleshwa'), ('NE', 'Nyeri'), ('LO', 'Loresho'), ('RU', 'Ruiru'), ('LM', 'Limuru'), ('KW', 'Kwale'), ('LI', 'Kilimani'), ('WN', 'Kahawa Wendani'), ('NU', 'Nyanyuki'), ('MV', 'Mvita'), ('WT', 'Watamu'), ('AR', 'Athi River'), ('KI', 'Kisii'), ('DA', 'Dagoretti'), ('NL', 'Nyali'), ('KM', 'Kiambu'), ('KR', 'Karen'), ('RK', 'Ruaka'), ('LK', 'Likoni'), ('KN', 'Kinoo')], max_length=2),
        ),
    ]
