# Generated by Django 2.1.5 on 2019-03-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_auto_20190311_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(choices=[('OR', 'Ongata Rongai'), ('NR', 'Narok'), ('SY', 'Syokimau'), ('NU', 'Nyanyuki'), ('NH', 'Nyahururu'), ('AR', 'Athi River'), ('KB', 'Kabete'), ('BU', 'Bungoma'), ('KW', 'Kwale'), ('KR', 'Karen'), ('LI', 'Kilimani'), ('KS', 'Kiserian'), ('RK', 'Ruaka'), ('KK', 'Kakamega'), ('IS', 'Isinya'), ('KM', 'Kiambu'), ('WN', 'Kahawa Wendani'), ('KU', 'Kikuyu'), ('NL', 'Nyali'), ('NA', 'Nakuru'), ('RU', 'Ruiru'), ('KA', 'Kajiado'), ('KI', 'Kisii'), ('LE', 'Kileleshwa'), ('MV', 'Mvita'), ('KL', 'Kilifi'), ('EL', 'Eldoret'), ('NG', 'Namanga'), ('MA', 'Malindi'), ('SU', 'Kahawa Sukari'), ('LA', 'Langata'), ('NV', 'Naivasha'), ('WS', 'Kahawa West'), ('ND', 'Nyandarua'), ('MC', 'Machakos'), ('LV', 'Lavington'), ('LM', 'Limuru'), ('WE', 'Westlands'), ('TH', 'Kithiani'), ('LK', 'Likoni'), ('WT', 'Watamu'), ('JJ', 'Juja'), ('NY', 'Nyamira'), ('KN', 'Kinoo'), ('MK', 'Mavoko'), ('LO', 'Loresho'), ('KT', 'Kitengela'), ('NE', 'Nyeri'), ('MS', 'Mombasa'), ('MW', 'Msambweni'), ('UK', 'Ukunda'), ('DA', 'Dagoretti'), ('SA', 'Kisauni')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('HT', 'Hotel'), ('RT', 'Restaurant'), ('RE', 'Resort'), ('SP', 'Spa'), ('GY', 'Gym'), ('AP', 'Apartment'), ('LD', 'Land'), ('CO', 'Coworking'), ('HO', 'Homes'), ('OF', 'Offices'), ('ST', 'Studios'), ('WR', 'Warehouse'), ('SH', 'Shops'), ('VR', 'Vacation Rental'), ('PU', 'Pop Up Store'), ('GA', 'Garden')], max_length=2),
        ),
    ]
