bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10,
  '11':11,
  '12':12,
  
  }

price_choices = {
  '20000': 'KES 20,000',
  '50000': 'KES 50,000',
  '100000':'KES 100,000',
  '200000':'KES 200,000',
  '300000':'KES 300,000',
  '400000':'KES 400,000',
  '500000':'KES 500,000',
  '600000':'KES 600,000',
  '700000':'KES 700,000',
  '800000':'KES 800,000',
  '900000':'KES 900,000',
  '1000000':'KES 1000,000',
  '5000000':'KES 5000,000',
  '10000000':'KES 10,000,000',
  '20000000':'KES 20,000,000',
}

city_choices = {
        'NA': 'Nairobi',
        'MS': 'Mombasa',
        'KS': 'Kisumu',
        'EL': 'Eldoret',
        'MA': 'Malindi',
        'KI': 'Kisii',
        'KK': 'Kakamega',
        'KU': 'Kikuyu',
        'KA': 'Kajiado',
        'KW': 'Kwale',
        'MC': 'Machakos',
        'NE': 'Nyeri',
        'NY': 'Nyamira',
        'BU': 'Bungoma',
        'NA': 'Nakuru',
        'NG': 'Ngong Road',
        'NU': 'Nanyuki',
        'AR': 'Athi River',
        'NV': 'Naivasha',
        'JJ': 'Juja',
        'LM': 'Lamu',
        'ND': 'Nyandarua',
        'IS': 'Isinya',
        'KT': 'Kitengela',
        'RU': 'Ruiru',
        'KL': 'Kilifi',
        'KM': 'Kiambu',
        'KS': 'Kiserian',
        'LM': 'Limuru',
        'WT': 'Watamu',
        'NR': 'Narok',
        'NH': 'Nyahururu',
        'OR': 'Ongata Rongai',
        'NG': 'Namanga',
        'MW': 'Msambweni',
        'KN': 'Kinoo',
        'UK': 'Ukunda',
        'LA': 'Langata',
        'WE': 'Westlands',
        'DA': 'Dagoretti',
        'KB': 'Kabete',
        'LI': 'Kilimani',
        'LE': 'Kileleshwa',
        'KR': 'Karen',
        'LV': 'Lavington',
        'LK': 'Likoni',
        'SY': 'Syokimau',
        'LO': 'Loresho',
        'WN': 'Kahawa Wendani',
        'SU': 'Kahawa Sukari',
        'TH': 'Kithiani',
        'WS': 'Kahawa West',
        'NL': 'Nyali',
        'SA': 'Kisauni',
        'MV': 'Mvita',
        'MK': 'Mavoko',
        'RK': 'Ruaka'
}

category_choices = {
    'AP': 'Apartments',
    'LD': 'Land',
    'CO': 'Coworking',
    'HO': 'Homes',
    'OF': 'Offices',
    'ST': 'Studios',
    'WR': 'Warehouse',
    'SH': 'Shop',
    'HT': 'Hotel',
    'RT': 'Restaurant',
    'RE': 'Resort',
    'SP': 'Spa',
    'GY': 'Gym',
    'VR': 'Vacation Rental',
    'PU': 'Pop Up',
    'GA': 'Garden'
}